<?php

declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';Auth::requireLogin();header('Cache-Control: no-store, no-cache, must-revalidate');header('Pragma: no-cache');$settings=SettingsService::all();$type=(string)($_GET['type']??'report');$printFont=match($settings['font_print']??'vazirmatn'){'system'=>'Tahoma,Arial,sans-serif','iransans'=>'IRANSansLocal,Vazirmatn,Tahoma,Arial,sans-serif',default=>'Vazirmatn,Tahoma,Arial,sans-serif'};
$title='گزارش';$headers=[];$rows=[];$tot=null;
if($type==='daily_report'){$r=AccountingService::reportWithRows((int)($_GET['id']??0));if(!$r)exit('گزارش پیدا نشد');$title='گزارش '.$r['company_name'].' '.AccountingService::displayBusinessDate((string)$r['report_date']);$headers=['نام','Username','کمیسیون','دلار دریافتی','دریافتی','دلار پرداختی','پرداختی'];foreach($r['rows'] as $x)$rows[]=[ $x['display_name_snapshot']?:($x['original_name_snapshot']?:$x['source_username']),$x['source_username'],$x['commission'],((float)$x['member_win']<0?abs((float)$x['member_win']):''),$x['received'],((float)$x['member_win']>0?(float)$x['member_win']:''),$x['paid']];$tot=['received'=>(float)$r['total_received'],'paid'=>(float)$r['total_paid'],'commission'=>(float)$r['total_commission'],'net'=>(float)$r['site_net']];}
elseif($type==='customer'){$c=CustomerService::get((int)($_GET['id']??0));if(!$c)exit('مشتری پیدا نشد');$title='حساب '.$c['display_name'];$headers=['تاریخ','شرکت','پنل','نام','Username','کمیسیون','دریافتی','پرداختی'];foreach($c['ledger']['rows'] as $r)$rows[]=[ AccountingService::displayBusinessDate((string)$r['report_date']),$r['company_name'],$r['panel_name'],$r['name'],$r['source_username'],$r['commission'],$r['received'],$r['paid']];$tot=$c['ledger']['totals'];}
else{$data=ReportingService::report($_GET);$typeTitle=match($data['type']){'daily'=>'روزانه','monthly'=>'ماهانه','multi'=>'چندماهه','detail'=>'ریز حساب',default=>$data['type']};$title='گزارش '.$typeTitle;if($data['type']==='detail'){$headers=['تاریخ','شرکت','پنل','نام','Username','کمیسیون','دریافتی','پرداختی'];foreach($data['rows'] as $r)$rows[]=[ AccountingService::displayBusinessDate((string)$r['report_date']),$r['company_name'],$r['panel_name'],$r['name'],$r['source_username'],$r['commission'],$r['received'],$r['paid']];}elseif(in_array($data['type'],['monthly','multi'],true)){$headers=['دوره','تعداد','دریافتی','پرداختی','کمیسیون','برد / باخت سایت'];foreach($data['rows'] as $r)$rows[]=[ $r['period'],$r['reports'],$r['received'],$r['paid'],$r['commission'],(($r['net']>0?'برد سایت ':($r['net']<0?'باخت سایت ':'تسویه ')).SettingsService::money(abs($r['net']),$settings))];}else{$headers=['تاریخ','شرکت','پنل','دریافتی','پرداختی','کمیسیون','برد / باخت سایت'];foreach($data['rows'] as $r)$rows[]=[ AccountingService::displayBusinessDate((string)$r['report_date']),$r['company_name'],$r['panel_name'],$r['received'],$r['paid'],$r['commission'],(($r['net']>0?'برد سایت ':($r['net']<0?'باخت سایت ':'تسویه ')).SettingsService::money(abs((float)$r['net']),$settings))];}$tot=$data['totals'];}
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=e($title)?></title><style>
<?php if(($settings['font_print']??'vazirmatn')==='vazirmatn' && !is_file(base_path('assets/fonts/vazirmatn-400.woff2'))):?>@import url("https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;700&display=swap");<?php endif;?>
<?php if(is_file(base_path('assets/fonts/vazirmatn-400.woff2'))):?>@font-face{font-family:Vazirmatn;src:url('/assets/fonts/vazirmatn-400.woff2') format('woff2');font-weight:400;font-style:normal;font-display:swap}<?php endif;?><?php if(is_file(base_path('assets/fonts/vazirmatn-700.woff2'))):?>@font-face{font-family:Vazirmatn;src:url('/assets/fonts/vazirmatn-700.woff2') format('woff2');font-weight:700;font-style:normal;font-display:swap}<?php endif;?><?php $iranFontFile=is_file(base_path('assets/fonts/Iranian-Sans.ttf'))?'assets/fonts/Iranian-Sans.ttf':(is_file(base_path('assets/fonts/Iranian Sans.ttf'))?'assets/fonts/Iranian Sans.ttf':'');?><?php if($iranFontFile!==''):?>@font-face{font-family:IRANSansLocal;src:url('/<?=e($iranFontFile)?>') format('truetype');font-weight:400 700;font-style:normal;font-display:swap}<?php endif;?><?=SettingsService::cssVars($settings)?>
*{box-sizing:border-box}html,body{margin:0;padding:0;background:#eef1f5;color:#000}body{font-family:<?=$printFont?>;padding:12px}.print-sheet,.print-sheet table,.print-sheet th,.print-sheet td,.toolbar button{font-family:<?=$printFont?>!important}.toolbar{position:sticky;top:0;z-index:5;display:flex;gap:8px;padding:8px;background:#eef1f5}.toolbar button{font:700 16px var(--font-form,Tahoma);padding:10px 14px;border:1px solid #222;border-radius:9px;background:#fff}.print-sheet{background:#fff;width:min(100%,1120px);margin:auto;padding:14px;box-shadow:0 6px 30px #0002;overflow:hidden}h1{text-align:center;font-size:22px;margin:0 0 5px}.meta{text-align:center;margin-bottom:10px;font-size:12px}.table-shell{width:100%;overflow:hidden}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1.6px solid #000;text-align:center;padding:5px 2px;font-size:clamp(8px,1.2vw,12px);line-height:1.35;overflow-wrap:anywhere}th{background:#eee;font-weight:800}.site-win{background:<?=SettingsService::themeFill($settings['theme_site_win']??$settings['theme_pay'],$settings)?>!important}.site-loss{background:<?=SettingsService::themeFill($settings['theme_site_loss']??$settings['theme_recv'],$settings)?>!important}.recv{background:<?=SettingsService::themeFill($settings['theme_recv'],$settings)?>}.pay{background:<?=SettingsService::themeFill($settings['theme_pay'],$settings)?>}.comm{background:<?=SettingsService::themeFill($settings['theme_comm'],$settings)?>}.totals{width:440px;max-width:100%;margin:14px 0 0 auto}.totals th,.totals td{font-size:12px}.font-warning{display:none;margin:8px 0;padding:8px;border:1px solid #eab308;background:#fff7cc;font-size:12px}
@media(max-width:700px){body{padding:4px}.toolbar{padding:5px}.toolbar button{font-size:14px;flex:1}.print-sheet{padding:6px;box-shadow:none}.print-sheet h1{font-size:18px}.meta{font-size:10px}th,td{font-size:clamp(6.2px,1.9vw,10px);padding:4px 1px}.totals{width:100%}}
@media print{@page{size:A4 landscape;margin:8mm}html,body{background:#fff}.toolbar,.font-warning{display:none!important}body{padding:0}.print-sheet{width:100%;max-width:none;padding:0;box-shadow:none;overflow:visible}h1{font-size:16pt}.meta{font-size:9pt}table{width:100%!important;table-layout:fixed}th,td{border:1pt solid #000!important;font-size:8.5pt;padding:3pt 1.5pt;line-height:1.2;-webkit-print-color-adjust:exact;print-color-adjust:exact}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.totals{width:105mm;page-break-inside:avoid}}
.toolbar{position:sticky!important;top:0!important;z-index:50!important;background:#fff!important;padding:8px!important}.toolbar button{min-height:42px}.site-win{background:var(--site-win)!important}.site-loss{background:var(--site-loss)!important}@media(max-width:700px){body{padding:0!important}.toolbar{display:grid!important;grid-template-columns:1fr 1fr!important}.print-sheet{width:100%!important;max-width:none!important;margin:0!important;padding:7px!important}.table-shell{overflow:hidden!important}table{table-layout:fixed!important;width:100%!important}th,td{font-size:clamp(7px,2vw,10px)!important;padding:3px 1px!important;overflow-wrap:anywhere}.totals{width:100%!important}.totals th,.totals td{font-size:11px!important}.meta{font-size:10px!important}}
</style></head><body><div class="toolbar"><button onclick="printWhenReady()">چاپ / ذخیره PDF</button><button onclick="goBackToApp()">بازگشت</button></div><main class="print-sheet"><div id="fontWarning" class="font-warning">فونت انتخابی روی هاست پیدا نشد و مرورگر از فونت جایگزین استفاده می‌کند.</div><h1><?=e($title)?></h1><div class="meta">واحد مبلغ: <?=e(SettingsService::moneyUnit($settings))?></div><div class="table-shell"><table><thead><tr><?php foreach($headers as $h):?><th><?=e($h)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($rows as $r):?><tr><?php foreach($r as $i=>$v):$h=$headers[$i]??'';$cl=str_contains($h,'دریافتی')?'recv':(str_contains($h,'پرداختی')?'pay':(str_contains($h,'کمیسیون')?'comm':(str_contains((string)$v,'برد سایت')?'site-win':(str_contains((string)$v,'باخت سایت')?'site-loss':''))));?><td class="<?=$cl?>"><?php if(is_numeric($v)&&in_array($h,['دریافتی','پرداختی','کمیسیون'],true)):?><?=e(SettingsService::money($v,$settings))?><?php elseif(is_numeric($v)&&str_contains($h,'دلار')):?><?=e(number_format((float)$v,2,'.',','))?><?php else:?><?=e($v)?><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php if($tot):?><table class="totals"><tr class="recv"><th>جمع دریافتی</th><td><?=e(SettingsService::money($tot['received']??0,$settings))?></td></tr><tr class="pay"><th>جمع پرداختی</th><td><?=e(SettingsService::money($tot['paid']??0,$settings))?></td></tr><tr class="comm"><th>جمع کمیسیون</th><td><?=e(SettingsService::money($tot['commission']??0,$settings))?></td></tr><?php $net=$tot['net']??(($tot['received']??0)-($tot['paid']??0));?><tr class="<?=$net>0?'site-win':($net<0?'site-loss':'comm')?>"><th><?=e($net>0?'برد سایت':($net<0?'باخت سایت':'تسویه'))?></th><td><?=e(SettingsService::money(abs($net),$settings))?></td></tr></table><?php endif;?></main><script>
function goBackToApp(){if(window.opener&&!window.opener.closed){window.close();return}if(history.length>1){history.back();return}location.href='index.php?page=analytics'}
(async()=>{try{await document.fonts.ready;const fam=getComputedStyle(document.body).fontFamily;if(fam.includes('Vazirmatn')&&!document.fonts.check('16px Vazirmatn'))document.getElementById('fontWarning').style.display='block';if(fam.includes('IRANSansLocal')&&!document.fonts.check('16px IRANSansLocal'))document.getElementById('fontWarning').style.display='block'}catch(e){}})();
</script><script>
async function printWhenReady(){
  try{ if(document.fonts && document.fonts.ready){ await document.fonts.ready; const fam=getComputedStyle(document.body).fontFamily; if(fam.includes('Vazirmatn')) await document.fonts.load('16px Vazirmatn'); if(fam.includes('IRANSansLocal')) await document.fonts.load('16px IRANSansLocal'); } }catch(e){}
  setTimeout(()=>window.print(),120);
}
window.addEventListener('beforeprint',()=>{document.documentElement.classList.add('fonts-ready-for-print')});
</script></body></html>
